#!/usr/bin/expect
set ipaddr3 [lindex $argv 0]
set timeout 3
set user "root"
set pw "root"
set hostname "192.168.0.$ipaddr3"
log_user 0
spawn ssh -o StrictHostKeyChecking=no $user@$hostname
log_user 1
expect {
    "password:" {
        send "$pw\r"
        expect "#"
        interact
    }
    timeout {
        send_error "mpssh: connect to host $hostname: Connection timed out\n"
        exit 1
    }
}
